-- MySQL Script generated by MySQL Workbench
-- 11/29/16 14:50:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tenant
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tenant
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tenant` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `tenant` ;

-- -----------------------------------------------------
-- Table `tenant`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tenant`.`room` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `room_number` VARCHAR(45) NULL COMMENT '',
  `electricity_meter` VARCHAR(45) NULL COMMENT '',
  `water_meter` VARCHAR(45) NULL COMMENT '',
  `rental_fee` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tenant`.`tenant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tenant`.`tenant` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(50) NULL COMMENT '',
  `date_entered` VARCHAR(45) NULL COMMENT '',
  `room_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `room_id`)  COMMENT '',
  INDEX `fk_tenant_room_idx` (`room_id` ASC)  COMMENT '',
  CONSTRAINT `fk_tenant_room`
    FOREIGN KEY (`room_id`)
    REFERENCES `tenant`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
